# Generated by Django 3.0.6 on 2020-05-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_app', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(),
        ),
    ]
