# Generated by Django 3.0.6 on 2020-05-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_app', '0005_auto_20200522_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.BooleanField(null=True),
        ),
    ]
