# Generated by Django 3.0.6 on 2020-05-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_app', '0007_auto_20200523_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.BooleanField(null=True),
        ),
    ]
